theme: jekyll-theme-minimal
title: A science for measuring cities
description: We're building better indicator frameworks for smart cities. [Read the GCTC slides]([Slides from GCTC 2017](https://github.com/indicator-frameworks/indicator-frameworks.github.io/raw/master/GCTC_2017.pdf).).

[Read the workshop paper](http://dl.acm.org/citation.cfm?id=3063762).
