theme: jekyll-theme-minimal
title: A science for measuring cities
description: We're building better indicator frameworks for smart cities. [Read the workshop paper](http://dl.acm.org/citation.cfm?id=3063762).
